export const ListShools = [
    "Trường THPT Chuyên Đại học Sư phạm Hà Nội",
    "Trường THPT chuyên Hà Nội - Amsterdam",
    "Trường THPT chuyên Nguyễn Huệ",
    "Trường THPT chuyên Ngoại ngữ",
    "Trường THPT chuyên Khoa học Tự nhiên",
    "Trường THPT chuyên Khoa học Xã hội và Nhân văn",
    "Trường THPT Chu Văn An",
    "Trường THPT Sơn Tây",
    "Trường THPT Phan Đình Phùng",
    "Trường THPT Phạm Hồng Thái",
    "Trường THPT Nguyễn Trãi - Ba Đình",
    "Trường THPT Tây Hồ",
    "Trường THPT Chu Văn An",
    "Trường THPT Trần Phú - Hoàn Kiếm",
    "Trường THPT Việt Đức",
    "Trường THPT Thăng Long",
    "Trường THPT Trần Nhân Tông",
    "Trường THPT Đoàn Kết - Hai Bà Trưng",
    "Trường THPT Kim Liên",
    "Trường THPT Đống Đa",
    "Trường THPT Quang Trung - Đống Đa",
    "Trường THPT Lê Quý Đôn - Đống Đa",
    "Trường THPT Trần Hưng Đạo - Thanh Xuân",
    "Trường THPT Nhân Chính",
    "Trường THPT Khương Đình",
    "Trường THPT Cầu Giấy",
    "Trường THPT Yên Hòa",
    "Trường THPT Việt Nam - Ba Lan",
    "Trường THPT Trương Định",
    "Trường THPT Hoàng Văn Thụ",
    "Trường THPT Lê Quý Đôn - Hà Đông",
    "Trường THPT Quang Trung - Hà Đông",
    "Trường THPT Trần Hưng Đạo - Hà Đông",
    "Trường THPT Yên Nghĩa",
    "Trường THPT Xuân Đỉnh",
    "Trường THPT Thượng Cát",
    "Trường THPT Nguyễn Thị Minh Khai",
    "Trường THPT Trung Văn",
    "Trường THPT Đại Mỗ",
    "Trường THPT Xuân Phương",
    "Trường THPT Mỹ Đình",
    "Trường THPT Lý Thường Kiệt",
    "Trường THPT Phúc Lợi",
    "Trường THPT Nguyễn Gia Thiều",
    "Trường THPT Thạch Bàn",
    "Trường THPT Cao Bá Quát - Gia Lâm",
    "Trường THPT Nguyễn Văn Cừ",
    "Trường THPT Dương Xá",
    "Trường THPT Yên Viên",
    "Trường THPT Sóc Sơn",
    "Trường THPT Đa Phúc",
    "Trường THPT Kim Anh",
    "Trường THPT Xuân Giang",
    "Trường THPT Trung Giã",
    "Trường THPT Minh Phú",
    "Trường THPT Ngô Thì Nhậm",
    "Trường THPT Đông Mỹ",
    "Trường THPT Nguyễn Quốc Trinh",
    "Trường THPT Ngọc Hồi",
    "Trường THPT Mê Linh",
    "Trường THPT Quang Minh",
    "Trường THPT Yên Lãng",
    "Trường THPT Tiến Thịnh",
    "Trường THPT Tự Lập",
    "Trường THPT Tiền Phong",
    "Trường THPT Đông Anh",
    "Trường THPT Liên Hà",
    "Trường THPT Cổ Loa",
    "Trường THPT Vân Nội",
    "Trường THPT Bắc Thăng Long",
    "Trường THPT Đan Phượng",
    "Trường THPT Hồng Thái",
    "Trường THPT Tân Lập",
    "Trường THPT Ngọc Tảo",
    "Trường THPT Phúc Thọ",
    "Trường THPT Vân Cốc",
    "Trường THPT Sơn Tây",
    "Trường THPT Tùng Thiện",
    "Trường THPT Xuân Khanh",
    "Trường THPT Quảng Oai",
    "Trường THPT Ngô Quyền - Ba Vì",
    "Trường THPT Minh Quang",
    "Trường THPT Ba Vì",
    "Trường THPT Bất Bạt",
    "Trường phổ thông Dân tộc Nội trú",
    "Trường THPT Hoài Đức A",
    "Trường THPT Hoài Đức B",
    "Trường THPT Hoài Đức C",
    "Trường THPT Vạn Xuân - Hoài Đức",
    "Trường THPT Quốc Oai",
    "Trường THPT Cao Bá Quát - Quốc Oai",
    "Trường THPT Minh Khai",
    "Trường THPT Phan Huy Chú - Quốc Oai",
    "Trường THPT Hai Bà Trưng - Thạch Thất",
    "Trường THPT Thạch Thất",
    "Trường THPT Phùng Khắc Khoan - Thạch Thất",
    "Trường THPT Bắc Lương Sơn",
    "Trường THPT Thanh Oai A",
    "Trường THPT Thanh Oai B",
    "Trường THPT Nguyễn Du - Thanh Oai",
    "Trường THPT Thường Tín",
    "Trường THPT Tô Hiệu - Thường Tín",
    "Trường THPT Vân Tảo",
    "Trường THPT Nguyễn Trãi - Thường Tín",
    "Trường THPT Lý Tử Tấn",
    "Trường THPT Chương Mỹ A",
    "Trường THPT Chương Mỹ B",
    "Trường THPT Chúc Động",
    "Trường THPT Xuân Mai",
    "Trường THPT Phú Xuyên A",
    "Trường THPT Phú Xuyên B",
    "Trường THPT Đồng Quan",
    "Trường THPT Tân Dân",
    "Trường THPT Ứng Hòa A",
    "Trường THPT Ứng Hòa B",
    "Trường THPT Trần Đăng Ninh",
    "Trường THPT Lưu Hoàng",
    "Trường THPT Đại Cường",
    "Trường THPT Mỹ Đức A",
    "Trường THPT Mỹ Đức B",
    "Trường THPT Mỹ Đức C",
    "Trường THPT Hợp Thanh",
    "Trường THPT Trần Quốc Tuấn",
    "Trường THPT Phan Huy Chú - Đống Đa",
    "Trường THPT Hoàng Cầu",
    "Trường THPT Lê Lợi",
    "Trường THCS - THPT Nguyễn Tất Thành",
    "Trường TH, THCS & THPT Thực nghiệm Khoa học Giáo dục",
    "Trường THPT Khoa học Giáo dục",
    "Trường THPT Lâm nghiệp",
    "Trường Phổ thông Năng khiếu Thể dục Thể thao Hà Nội",
    "Trường Trung học phổ thông Lương Thế Vinh",
    "Trường phổ thông liên cấp Đa Trí Tuệ (MIS)",
    "Trường Trung học phổ thông Lê Quý Đôn",
    "Trường Trung học phổ thông Xuân Thủy",
    "Trường Trung học phổ thông Đào Duy Từ",
    "Trường THPT Huỳnh Thúc Kháng",
    "Trường THPT Xala",
    "Trường THPT Phan Chu Trinh",
    "Trường phổ thông võ thuật Bảo Long",
    "Trường THPT Việt Hoàng",
    "Trường THPT Vạn Xuân - Long Biên",
    "Trường THPT Văn Lang",
    "Trường THPT Văn Hiến",
    "Trường THPT Trí Đức",
    "Trường THPT Phan Bội Châu",
    "Trường THPT Trần Thánh Tông",
    "Trường THPT Trần Quang Khải",
    "Trường THPT Trần Phú - Ba Vì",
    "Trường THPT Trần Đại Nghĩa",
    "Trường THPT Tô Hiệu - Gia Lâm",
    "Trường THPT Tô Hiến Thành",
    "Trường THPT Thanh Xuân",
    "Trường THPT Tây Sơn",
    "Trường THPT Tây Đô",
    "Trường THPT Phương Nam",
    "Trường THPT Phùng Khắc Khoan - Đống Đa",
    "Trường THPT Phú Bình",
    "Trường THPT Phạm Văn Đồng",
    "Trường THPT Nguyễn Văn Huyên",
    "Trường THPT Nguyễn Tộ",
    "Trường THPT Nguyễn Tất Thành - Sơn Tây",
    "Trường THPT Nguyễn Du - Mê Linh",
    "Trường THPT Nguyễn Đình Chiểu",
    "Trường THPT Ngô Tất Tố",
    "Trường THPT Ngô Sĩ Liên",
    "Trường THPT Ngô Quyền - Đông Anh",
    "Trường THPT Ngô Gia Tự",
    "Trường THPT Minh Trí",
    "Trường THPT Mai Hắc Đế",
    "Trường THPT Mạc Đĩnh Chi",
    "Trường THPT Lý Thánh Tông",
    "Trường THPT Lý Thái Tổ",
    "Trường THPT Lương Văn Can",
    "Trường THPT Lương Thế Vinh - Ba Vì",
    "Trường THPT Lê Văn Thiêm - Gia Lâm",
    "Trường THPT Lê Thánh Tông",
    "Trường THPT Lê Ngọc Hân",
    "Trường THPT Lam Hồng",
    "Trường THPT Lạc Long Quân",
    "Trường THPT Kinh Đô",
    "Trường Phổ thông nội trú IVS",
    "Trường THPT Hồng Hà",
    "Trường THPT Hồng Đức",
    "Trường THPT Hồng Bàng",
    "Trường THPT Hoàng Mai",
    "Trường THPT Hoàng Long",
    "Trường THPT Hoàng Diệu",
    "Trường THPT Hồ Xuân Hương",
    "Trường THPT Hồ Tùng Mậu",
    "Trường THPT Hermann Gmeiner Hà Nội",
    "Trường THPT Hà Đông",
    "Trường THPT Green City Academy",
    "Trường THPT Einstein",
    "Trường THPT Đông Kinh",
    "Trường THPT Đông Đô",
    "Trường THPT dân lập Phan Chu Trinh",
    "Trường THPT Đinh Tiên Hoàng - Ba Đình",
    "Trường THPT Đặng Tiến Đông",
    "Trường THPT Đặng Thai Mai",
    "Trường THPT dân lập Hà Nội",
    "Trường THPT Đại Việt",
    "Trường THPT Bình Minh",
    "Trường THPT Bắc Đuống",
    "Trường THPT An Dương Vương",
    "Trường THPT Hà Thành",
    "Trường THPT Tạ Quang Bửu",
    "Trường THPT M.V.Lômônôxốp",
    "Trường THPT Phùng Hưng",
    "Trường THPT Nguyễn Trực",
    "Trường THPT Nguyễn Trường Tộ",
    "Trường THPT Bắc Hà - Đống Đa",
    "Trường THPT Ngô Gia Tự",
    "Trường THPT Ngô Sĩ Liên",
    "Trường THPT Phùng Hưng",
    "Trường THPT Nguyễn Bỉnh Khiêm - Phú Xuyên",
    "Trường THPT Nguyễn Thượng Hiền - Ứng Hòa",
    "Trường THPT Lương Văn Can - Cầu Giấy",
    "Trường THPT Marie Curie",
    "Trường THPT Nguyễn Bỉnh Khiêm",
    "Trường Phổ thông FPT",
    "Trường Phổ thông TH School",
    "Trường THPT Ban Mai",
    "Trường THPT Nguyễn Huệ",
    "Trường THPT Phạm Ngũ Lão",
    "Trường THPT Phan Huy Chú - Thạch Thất",
    "Trường Phổ thông liên cấp Vinschool",
    "Trường TH, THCS & THPT Archimedes Đông Anh",
    "Trường THPT IVS",
    "Trường THPT Global",
    "Trường Phổ thông Song ngữ Liên cấp Wellspring",
    "Trường THPT Quốc tế Thăng Long",
    "Trường Phổ thông Liên cấp Olympia",
    "Trường Phổ thông Liên cấp Newton",
    "Trường Song ngữ Quốc tế Hà Nội Academy",
    "Trường THPT Đoàn Thị Điểm",
    "Trường Phổ thông Liên cấp Alfred Nobel",
    "Trường Phổ thông Liên cấp\nViệt - Úc, Hà Nội",
    "Trường Phổ thông liên cấp Nguyễn Siêu",
    "Trường Phổ thông liên cấp TH School Hòa Lạc",
    "Trường Phổ thông Quốc tế Việt Nam (VIS)",
    "Trường Phổ thông Liên cấp Hòa Bình Latrobe - Hà Nội",
    "Trường Phổ thông Liên cấp Vinschool The Harmony",
    "Trường Phổ thông Liên cấp Hà Nội Adelaide School (H.A.S)",
    "Trường Quốc tế Đa cấp Anh Việt Hoàng gia (BVIS Royal)",
    "Trường Quốc tế Đa cấp Anh - Hà Nội (BIS Hanoi)",
    "Trường Hàn Quốc tại Hà Nội",
    "Trường Quốc tế Nhật Bản",
    "Trường Quốc tế Pháp Alexandre Yersin",
    "Trường Phổ thông Quốc tế Hà Nội (HIS)",
    "Trường Quốc tế Liên Hợp Quốc Hà Nội(UNIS Hanoi)",
    "Trường Phổ thông đa cấp Concordia Hanoi",
    "Trường Phổ thông Song ngữ Quốc tế Horizon",
    "Trường Phổ thông Quốc tế Singapore (tại Hà Nội)",
    "Trường Phổ thông Quốc tế St.Paul",
    "Trường phổ thông quốc tế ParkCity Hà Nội"
]